version: '2'
services:
  payment-challenge:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: payment-challenge
    ports:
    - "8080:8080"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
      MYSQL_DB_URL: jdbc:mysql://mysql-local:3306/challenge?useSSL=false
    links:
    - mysql-local
    depends_on:
    - mysql-local
  mysql-local:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge

volumes:
  db_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.0.0/24
        gateway: 172.21.0.1